/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

//import Atxy2k.CustomTextField.RestrictedTextField;

/**
 *
 * @author Gustavo Davila
 */
public class ViewVenta extends javax.swing.JFrame {

    /**
     * Creates new form ViewVenta
     */
    public ViewVenta() {
        initComponents();
        this.setTitle("Venta");
        this.setLocationRelativeTo(this); 
        
        //RestrictedTextField res_id = new RestrictedTextField(this.caja_id); 
        //res_id.setOnlyNums(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        caja_areatexto = new javax.swing.JTextArea();
        vender_boton = new javax.swing.JButton();
        caja_id = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        salir_venta_boton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        caja_cantidad = new javax.swing.JTextField();
        facturar_boton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        caja_areaVentas = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        caja_buscar = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        buscarBoton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabelfondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        caja_areatexto.setColumns(20);
        caja_areatexto.setRows(5);
        jScrollPane1.setViewportView(caja_areatexto);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 360, 170));

        vender_boton.setText("Añadir Producto");
        getContentPane().add(vender_boton, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 360, 130, -1));

        caja_id.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                caja_idKeyTyped(evt);
            }
        });
        getContentPane().add(caja_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 360, 60, -1));

        jLabel1.setForeground(new java.awt.Color(240, 240, 240));
        jLabel1.setText("Id Prod: ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, 50, 20));

        salir_venta_boton.setText("Salir");
        getContentPane().add(salir_venta_boton, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 460, 110, -1));

        jLabel2.setForeground(new java.awt.Color(240, 240, 240));
        jLabel2.setText("Cantidad:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 360, 60, 20));

        caja_cantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caja_cantidadActionPerformed(evt);
            }
        });
        caja_cantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                caja_cantidadKeyTyped(evt);
            }
        });
        getContentPane().add(caja_cantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 360, 60, -1));

        facturar_boton.setText("Facturar");
        getContentPane().add(facturar_boton, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 460, 100, -1));

        caja_areaVentas.setColumns(20);
        caja_areaVentas.setRows(5);
        caja_areaVentas.setText("\n");
        jScrollPane2.setViewportView(caja_areaVentas);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 160, 210, 170));

        jLabel3.setForeground(new java.awt.Color(240, 240, 240));
        jLabel3.setText("Productos añadidos");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 130, 120, -1));
        getContentPane().add(caja_buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 250, -1));

        jLabel4.setForeground(new java.awt.Color(240, 240, 240));
        jLabel4.setText("Nombre Producto: ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 100, 20));

        buscarBoton.setText("Buscar");
        getContentPane().add(buscarBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 60, 100, -1));

        jLabel5.setForeground(new java.awt.Color(240, 240, 240));
        jLabel5.setText("Información productos");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, -1, -1));

        jLabelfondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/fondo via2.jpg"))); // NOI18N
        getContentPane().add(jLabelfondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void caja_idKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_caja_idKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        
        if(c< '0' || c>'9')evt.consume();
    }//GEN-LAST:event_caja_idKeyTyped

    private void caja_cantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caja_cantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_caja_cantidadActionPerformed

    private void caja_cantidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_caja_cantidadKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        
        if(c< '0' || c>'9')evt.consume(); 
    }//GEN-LAST:event_caja_cantidadKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewVenta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton buscarBoton;
    public javax.swing.JTextArea caja_areaVentas;
    public javax.swing.JTextArea caja_areatexto;
    public javax.swing.JTextField caja_buscar;
    public javax.swing.JTextField caja_cantidad;
    public javax.swing.JTextField caja_id;
    public javax.swing.JButton facturar_boton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelfondo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JButton salir_venta_boton;
    public javax.swing.JButton vender_boton;
    // End of variables declaration//GEN-END:variables
}
